### ISSUE TITLE
Would it be possible to let people use their own SYS1.MACLIB?

### ISSUE THREAD

**Issue by moshix** [SYSPROG-JLS/S370BALAsm#4]
Hello Jim

Given that we have SYS1.MACLIB and AMOGEN etc. in MVS 3.8, would it be possible to use a series of those macros for certain common things, like PUT GET OPEN AND CLOSE and then just provide slightly modified macros for those?

thanks

M

**Comment by SYSPROG-JLS** [comment]
Hi Moshix,
You mean you would like, for compatibility purposes, the assembler to accept PUT GET OPEN AND CLOSE and expand the macro with code compatible with S370BALEmu emulator?

Jim

**Comment by moshix** [comment]
Jim

yes and so users could over time adapt the SYS1.MACLIB to work on the PC. I would certainly contribute to adapt the macro library for the most important functions (and of course also the SVCs that go with them). 

if there was a switch like -maclib /path_to_maclib then your assembler could look for macros there. SAVE and RETURN would be easy to implement as no SVCs are needed at all. :-)

thanks

M

**Comment by SYSPROG-JLS** [comment]
M,

(restating my recent e-mail - as a way to close the issue)

At this point in time I don't want to tackle the significant task of writing even a modest macro interpreter that would need to include support for even a basic conditional assembly language. So that puts on hold your idea of using external MACLIBs for now.

thanks for all your help!
Jim
